# Generated by Django 3.2.18 on 2024-12-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': (), 'verbose_name': 'patient', 'verbose_name_plural': 'patient'},
        ),
    ]
