# Generated by Django 3.2.18 on 2024-12-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': (('AddAdmin', 'Can add admin'), ('ShowAdmin', 'Show all admin'), ('DoctorSpecializations', 'show doctor in same Specializations')), 'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
    ]
